create table if not exists public.short_links (
    id bigint generated by default as identity primary key,
    short_code text not null unique,
    original_url text not null,
    click_count bigint not null default 0,
    created_at timestamp with time zone not null default now()
);

-- Enable RLS
alter table public.short_links enable row level security;

-- Allow anonymous and authenticated read access (so redirects work)
create policy "Allow public read access to short links"
on public.short_links for select
to public
using (true);

-- Allow anonymous and authenticated insert access (for creating new links)
create policy "Allow public insert access to short links"
on public.short_links for insert
to public
with check (true);

-- Create an RPC function to atomically increment click count
create or replace function increment_click_count(p_short_code text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    update short_links
    set click_count = click_count + 1
    where short_code = p_short_code;
end;
$$;
